name: Test actions crypto
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo abc > test.file
      - name: Hello world
        uses: ./
        with:
          crypto-path: test.file
          crypto-action: enc
          crypto-password: 123456
        
